
[database]
# 你的数据库连接
mongo_connection_string = "mongodb://user:password@ip:port/"

[nonebot]
# 这里的配置会被转发到.env, 无需设置

[logging]
# 日志级别 debug/info/warn/error/crit
level = "debug"
# 是否接管nonebot的日志
inject_nonebot = true

[general]
# 超级用户列表
superusers = [1111111111, 1234567890]

# 注释掉的配置都是可选项, 会影响部分功能但不会影响运行

# MCSManager配置
# [mcsm]
# 面板的url, 格式不可以改动(比如少加多加https或者后面的/什么的
# base_url = "http://127.0.0.1:23333/"
# 你的API key
# key = "YOUR_KEY"
# 日志转发忽略的实例名称(防止循环转发)
# ignored = ["bot"]